version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser || {POSTGRES_USER}
      POSTGRES_PASSWORD: mypassword || {POSTGRES_PASSWORD}
      POSTGRES_DB: mydb || {POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb || {SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: myuser || {SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: mypassword || {SPRING_DATASOURCE_PASSWORD}

volumes:
  database_data: