name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-

    steps:
      - uses: actions/checkout@v4
      - name: build the project
        run: ./gradlew build
      - name: Build the Docker image
        run: docker build -t my-image-name .